// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDutY_GfCNWeZmhEZ4wKqljIFgEuXE4hdU',
    appId: '1:501364080666:web:81584f9b03af28f2c091a3',
    messagingSenderId: '501364080666',
    projectId: 'app-firebase-88d0e',
    authDomain: 'app-firebase-88d0e.firebaseapp.com',
    storageBucket: 'app-firebase-88d0e.firebasestorage.app',
    measurementId: 'G-YNR59V6MDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5o7-YMrSZbjbNzQJqXCN1q4BhV8cWzIk',
    appId: '1:501364080666:android:65d838d774661820c091a3',
    messagingSenderId: '501364080666',
    projectId: 'app-firebase-88d0e',
    storageBucket: 'app-firebase-88d0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBtG2538WTGduk2pEi-QPtWhqhIOCHcac',
    appId: '1:501364080666:ios:c773729240cc83bdc091a3',
    messagingSenderId: '501364080666',
    projectId: 'app-firebase-88d0e',
    storageBucket: 'app-firebase-88d0e.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBtG2538WTGduk2pEi-QPtWhqhIOCHcac',
    appId: '1:501364080666:ios:c773729240cc83bdc091a3',
    messagingSenderId: '501364080666',
    projectId: 'app-firebase-88d0e',
    storageBucket: 'app-firebase-88d0e.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDutY_GfCNWeZmhEZ4wKqljIFgEuXE4hdU',
    appId: '1:501364080666:web:3290a86988129aafc091a3',
    messagingSenderId: '501364080666',
    projectId: 'app-firebase-88d0e',
    authDomain: 'app-firebase-88d0e.firebaseapp.com',
    storageBucket: 'app-firebase-88d0e.firebasestorage.app',
    measurementId: 'G-LGYCKNH37F',
  );
}
